# fly.toml app configuration file generated for ai-magazine-article-api on 2026-05-26T16:48:20+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-magazine-article-api'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  RAILS_ENV = 'production'
  WEB_ORIGIN = 'https://ai-magazine-article-generator.vercel.app'

[[mounts]]
  source = 'sqlite_data'
  destination = '/rails/storage'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
