source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.1.3"
gem "sqlite3", "~> 1.7"
gem "puma", ">= 5.0"
gem "rack-cors", "~> 2.0"
gem "rexml", "~> 3.4"
gem "rubyzip", "~> 2.3"

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
end
